`ifndef CHAIN2_CFG_VH
`define CHAIN2_CFG_VH

`define CHAIN2_CONV_CIN 3
`define CHAIN2_CONV_COUT 64
`define CHAIN2_CONV_H_IN 19
`define CHAIN2_CONV_W_IN 19
`define CHAIN2_CONV_KH 3
`define CHAIN2_CONV_KW 3
`define CHAIN2_CONV_STRIDE 2
`define CHAIN2_CONV_PAD 0
`define CHAIN2_CONV_H_OUT 9
`define CHAIN2_CONV_W_OUT 9
`define CHAIN2_CONV_K_REAL 27
`define CHAIN2_CONV_K_TILES 1
`define CHAIN2_CONV_N_TILES 2
`define CHAIN2_CONV_ACT_ZP 115
`define CHAIN2_CONV_Y_ZP 0
`define CHAIN2_POOL_H_OUT 4
`define CHAIN2_POOL_W_OUT 4
`define CHAIN2_POOL_KH 3
`define CHAIN2_POOL_KW 3
`define CHAIN2_POOL_STRIDE 2
`define CHAIN2_POOL_PAD 0

`endif
